 export const fooddata = [{
  'id': 1,
  'title': 'Dosa',
  'imageuri': 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/dosa-recipe.jpg',
  'time': 30,
  'isVeg': true,
  'category': 'veg',
  'rating': 3,
  'description': 'Crispy South Indian dosa made from fermented rice and urad dal batter',
  'ingredients': ["2 cups rice", "1/2 cup urad dal (split black gram)", "1/2 teaspoon fenugreek seeds", "Salt to taste", "Water for soaking and grinding", "Oil or ghee for cooking dosa"],
  'procedure': [
    "Wash the rice, urad dal, and fenugreek seeds together under running water. Soak them in water for about 4-6 hours.",
    "After soaking, drain the water and grind the rice, urad dal, and fenugreek seeds together to make a smooth batter. You can add water as needed while grinding to achieve the desired consistency. The batter should be slightly thick but not too thick.",
    "Add salt to the batter and mix well. Cover the batter with a lid and let it ferment in a warm place for about 8-12 hours or until it doubles in volume. Fermentation time may vary depending on the weather.",
    "Once the batter has fermented, gently mix it and adjust the consistency with a little water if needed. The batter should be of pouring consistency.",
    "Heat a non-stick or cast-iron skillet (tawa) over medium heat. Spread a little oil or ghee on the tawa using a piece of cloth or onion slice to grease it.",
    "Pour a ladleful of dosa batter onto the center of the tawa. Using the back of the ladle, spread the batter in a circular motion to form a thin and even dosa.",
    "Drizzle a little oil or ghee around the edges of the dosa and on top.",
    "Cook the dosa until the bottom turns golden brown and crispy. Flip the dosa using a spatula and cook the other side for a minute or until it's cooked and slightly crispy.",
    "Fold the dosa in half or roll it up and remove it from the tawa.",
    "Serve the hot and crispy dosa with sambar, coconut chutney, or any accompaniment of your choice."
  ]

},
{
  'id': 2,
  'title': 'Pongal',
  'imageuri': 'https://www.indianveggiedelight.com/wp-content/uploads/2021/11/ven-pongal-featured.jpg',
  'time': 60,
  'isVeg': true,
  'category': 'veg',
  'rating': 3,
  'description': 'Delicious South Indian dish made with rice, lentils, and spices',
  'ingredients': ['1 Cup Rice', '2 TableSpoon Ghee', '1 pinches asafoetida', '1 handful curry leaves', '5 cashews', '5 cashews', '1/2 teaspoon turmeric', '1/2 teaspoon black pepper', '1 teaspoon cumin seeds', '2 teaspoon ginger paste', '1 cup moong dal', 'salt as required'],
  'procedure': [
    "Wash the rice and moong dal together under running water until the water runs clear. Soak them in water for about 15-20 minutes. Drain and set aside.",
    "In a large pot or pressure cooker, add the soaked rice and moong dal. Add water and turmeric powder. Mix well.",
    "Place the pot on the stove and cook the rice and dal mixture. If using a pressure cooker, close the lid without the weight and cook for about 3-4 whistles on medium heat. If using a pot, bring the mixture to a boil and then let it simmer until the rice and dal are fully cooked and mushy.",
    "Once the rice and dal are cooked, mash them well using a wooden spoon or a masher. The consistency of Pongal should be slightly mushy but not too runny.",
    "In a separate pan, heat ghee and oil together.",
    "Add cumin seeds and let them splutter.",
    "Add black pepper, grated ginger, and asafoetida. Sauté for a few seconds until aromatic.",
    "Add cashew nuts and sauté until they turn golden brown.",
    "Add the chopped vegetables and cook them until they are tender.",
    "Pour the ghee and spice mixture into the cooked rice and dal mixture. Mix well.",
    "Add salt to taste and mix again.",
    "Let the Pongal simmer for a few minutes on low heat, allowing all the flavors to blend.",
    "Taste and adjust the seasoning if needed.",
    "Serve hot Pongal with coconut chutney, sambar, or any other accompaniment of your choice."
  ]
},
{
  'id': 3,
  'title': 'chicken briyani',
  'imageuri': 'https://t3.ftcdn.net/jpg/01/14/51/60/360_F_114516029_Z2B6FO30AB6ZR3v9WHXjpXmJScaiLtzk.jpg',
  'time': 120,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 5,
  'description': 'Flavorful rice dish cooked with aromatic spices and tender chicken, a favorite in Indian cuisine',
  'ingredients': ['2 cups Basmati rice', '500g Chicken, cut into pieces', '1 cup Yogurt', '2 Onions, thinly sliced', '2 Tomatoes, chopped', '1/4 cup Mint leaves, chopped', '1/4 cup Cilantro leaves, chopped', '4 Green chilies, slit', '1 tablespoon Ginger paste', '1 tablespoon Garlic paste', '1/2 cup Cooking oil', '4 tablespoons Ghee', '1/2 teaspoon Turmeric powder', '1 teaspoon Red chili powder', '1 teaspoon Garam masala powder', '1 teaspoon Biryani masala powder', '1/4 teaspoon Saffron strands soaked in milk', '1 Lemon, juice extracted', 'Salt to taste', 'Water for cooking rice'],
  'procedure': [
    "Wash the basmati rice in water until the water runs clear. Soak the rice in water for 30 minutes. Drain and set aside.",
    "In a large bowl, marinate the chicken pieces with yogurt, ginger paste, garlic paste, turmeric powder, red chili powder, biryani masala powder, half of the chopped mint leaves, half of the chopped cilantro leaves, and salt. Let it marinate for at least 1 hour.",
    "In a heavy-bottomed pot, heat oil and ghee over medium heat.",
    "Add sliced onions and sauté until they turn golden brown and crispy. Remove half of the fried onions and set them aside for garnishing.",
    "Add the marinated chicken to the pot and cook until it changes color and is partially cooked.",
    "Add chopped tomatoes and cook until they become soft and the oil starts to separate.",
    "Add the remaining mint leaves and cilantro leaves. Mix well.",
    "Layer the partially cooked chicken with the soaked and drained rice in the pot. Spread them evenly.",
    "Pour saffron-soaked milk, lemon juice, and garam masala powder over the rice.",
    "Add the remaining fried onions on top.",
    "Close the pot with a tight-fitting lid and cook on low heat for about 20-25 minutes, until the rice and chicken are fully cooked and the flavors are well absorbed.",
    "Once done, remove from heat and let the biryani rest for 10-15 minutes before opening the lid.",
    "Gently fluff the biryani with a fork to mix the rice and chicken layers.",
    "Serve the aromatic Chicken Biryani with raita, salad, or any accompaniment of your choice."
  ]

},
{
  'id': 4,
  'title': 'idly',
  'imageuri': 'https://media.istockphoto.com/id/638506124/photo/idli-with-coconut-chutney-and-sambhar.jpg?s=612x612&w=0&k=20&c=ze1ngBM0LY4w9aqWx_tGe2vTAr4uf36elveTDZ83fgw=',
  'time': 60,
  'isVeg': true,
  'category': 'veg',
  'rating': 2,
  'description': 'Classic and fluffy South Indian steamed rice cakes',
  'ingredients': ['2 cups idli rice', '1/2 cup urad dal (split black gram)', '1/2 teaspoon fenugreek seeds', 'Salt to taste', 'Water for soaking and grinding', 'Oil or ghee for greasing idli molds'],
  'procedure': [
    "Wash the idli rice and urad dal separately under running water until the water runs clear.",
    "Soak the idli rice and urad dal along with fenugreek seeds in enough water for about 4-6 hours.",
    "After soaking, drain the water from both the rice and dal.",
    "Grind the urad dal with fenugreek seeds using a wet grinder or mixer grinder until smooth and fluffy. Add water as needed.",
    "Transfer the urad dal batter to a large mixing bowl.",
    "Next, grind the soaked idli rice until it becomes a smooth batter. Add water as needed.",
    "Mix the rice batter with the urad dal batter. Add salt and mix well. The batter should be of pouring consistency.",
    "Cover the batter and let it ferment in a warm place for 8-10 hours or until it doubles in volume.",
    "Once the batter has fermented, mix it gently to incorporate air and give it a good stir.",
    "Grease the idli molds with oil or ghee to prevent sticking.",
    "Pour the batter into the idli molds, filling each mold 3/4 full.",
    "Steam the idlis in a steamer for about 10-12 minutes, or until a toothpick inserted into the center comes out clean.",
    "Allow the idlis to cool for a few minutes before removing them from the molds.",
    "Serve the soft and fluffy idlis with coconut chutney, sambar, or your favorite accompaniment.",
  ]

},
{
  'id': 5,
  'title': 'poori',
  'imageuri': 'https://img.freepik.com/premium-photo/poori-masala-curry-aloo-sabzi-puri_466689-77508.jpg?w=2000',
  'time': 80,
  'isVeg': true,
  'category': 'veg',
  'rating': 5,
  'description': 'Deep-fried, golden and puffy Indian bread',
  'ingredients': ['2 cups whole wheat flour', '1/2 teaspoon salt', '1 teaspoon sugar', '1 tablespoon ghee or oil', '3/4 cup water (approximately)', 'Oil for deep frying'],
  'procedure': [
    "In a mixing bowl, combine whole wheat flour, salt, sugar, and ghee or oil.",
    "Gradually add water and knead the mixture to form a smooth and firm dough.",
    "Cover the dough with a damp cloth and let it rest for about 15-20 minutes.",
    "Divide the dough into small equal-sized balls and flatten slightly with your hands.",
    "Heat oil in a deep frying pan over medium heat.",
    "Roll each dough ball into a 3-4 inch circular shape using a rolling pin.",
    "Slide the rolled poori into the hot oil and press gently with a slotted spoon.",
    "Fry until the poori puffs up and turns golden brown on both sides.",
    "Remove the fried poori from the oil and place on a paper towel to drain excess oil.",
    "Repeat the process with the remaining dough balls, frying one poori at a time.",
    "Serve the hot and puffy pooris with a side dish like potato masala or chana masala.",
  ]

},
{
  'id': 6,
  'title': 'chicken 65',
  'imageuri': 'https://media.istockphoto.com/id/1265210223/photo/fried-chicken-kebab-or-kabab.jpg?s=612x612&w=0&k=20&c=eE-Y8lm6xSrFpmOLM-lXwZq7XFSmFJpRk19H4qM2RQE=',
  'time': 50,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 5,
  'description': 'Spicy and flavorful Indian fried chicken bites, a crowd-pleaser on your Food Recipe App',
  'ingredients': ['500g boneless chicken pieces,', '2 tablespoons yogurt,', '1 tablespoon lemon juice,', '1 teaspoon ginger paste,', '1 teaspoon garlic paste,', '1/2 teaspoon red chili powder,', '1/2 teaspoon turmeric powder,', '1 teaspoon garam masala,', '1 teaspoon cumin powder,', '1 teaspoon coriander powder,', '1 teaspoon fennel seeds,', '10-12 curry leaves,', '2 green chilies, chopped,', '2 tablespoons corn flour,', '2 tablespoons all-purpose flour,', 'Salt to taste,', 'Oil for deep frying,', 'Chopped coriander leaves for garnishing,', 'Lemon wedges for serving,'],
  'procedure': [
    "In a bowl, mix yogurt, lemon juice, ginger paste, garlic paste, red chili powder, turmeric powder, garam masala, cumin powder, coriander powder, and salt to make a marinade.",
    "Add the boneless chicken pieces to the marinade, coat well, and let it marinate for at least 1-2 hours in the refrigerator.",
    "In a separate bowl, mix corn flour and all-purpose flour together.",
    "Coat each marinated chicken piece with the flour mixture and shake off excess flour.",
    "Heat oil in a deep frying pan over medium-high heat.",
    "Fry the coated chicken pieces in batches until they are golden brown, crispy, and fully cooked. Drain on paper towels.",
    "In a separate pan, heat a little oil and add fennel seeds, curry leaves, and chopped green chilies.",
    "Add the fried chicken pieces to the pan and toss well to coat with the tempering.",
    "Garnish with chopped coriander leaves and serve hot with lemon wedges.",
  ]

},
{
  'id': 7,
  'title': 'fish fry',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGkU_fuAbJ23gkK4O2evP-G69waVeSLRu0-w&usqp=CAU',
  'time': 40,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 4,
  'description': 'Crispy and seasoned fried fish, a mouthwatering seafood dish featured on Food Recipe App',
  'ingredients': ['500g fish fillets,', '1 tablespoon red chili powder,', '1/2 teaspoon turmeric powder,', '1 teaspoon ginger paste,', '1 teaspoon garlic paste,', '1 teaspoon cumin powder,', '1 teaspoon coriander powder,', '1/2 teaspoon black pepper powder,', '1 teaspoon lemon juice,', 'Salt to taste,', '2 tablespoons rice flour,', '2 tablespoons all-purpose flour,', 'Oil for shallow frying,'],
  'procedure': [
    "In a bowl, mix red chili powder, turmeric powder, ginger paste, garlic paste, cumin powder, coriander powder, black pepper powder, lemon juice, and salt to make a marinade.",
    "Coat the fish fillets with the marinade and let them marinate for about 30 minutes.",
    "In a separate bowl, mix rice flour and all-purpose flour together.",
    "Coat each marinated fish fillet with the flour mixture and shake off excess flour.",
    "Heat oil in a frying pan over medium-high heat for shallow frying.",
    "Place the coated fish fillets in the hot oil and fry until they are crispy and golden brown on both sides.",
    "Remove from the oil and drain on paper towels to remove excess oil.",
    "Serve the delicious fish fry hot with lemon wedges and your favorite dipping sauce.",
  ]

},
{
  'id': 8,
  'title': 'porrata',
  'imageuri': 'https://images.news18.com/ibnlive/uploads/2022/06/malabar-paratha.jpg',
  'time': 60,
  'isVeg': true,
  'category': 'veg',
  'rating': 4,
  'description': 'Spicy and flavorful Indian fried chicken bites, a crowd-pleaser on your Food Recipe App',
  'ingredients': ['2 cups whole wheat flour,', '1/2 teaspoon salt,', 'Water for kneading,', 'Ghee or oil for cooking,'],
  'procedure': [
    "In a mixing bowl, combine whole wheat flour and salt.",
    "Gradually add water and knead to form a soft and smooth dough. The dough should not be too sticky or too dry.",
    "Cover the dough with a damp cloth and let it rest for about 15-20 minutes.",
    "Divide the dough into small equal-sized balls.",
    "Take one dough ball and roll it into a small disc using a rolling pin.",
    "Spread a little ghee or oil on the rolled disc.",
    "Fold the disc in half, applying some more ghee or oil on the folded side.",
    "Fold it again to form a triangle or semi-circle.",
    "Roll out the triangle or semi-circle gently to make a thin paratha.",
    "Heat a tawa or griddle over medium-high heat.",
    "Place the rolled paratha on the hot tawa and cook until small bubbles appear on the surface.",
    "Flip the paratha and cook the other side. Apply ghee or oil on both sides and cook until golden brown spots appear.",
    "Remove the paratha from the tawa and place it in a serving dish.",
    "Repeat the process with the remaining dough balls.",
    "Serve the delicious and flaky parathas hot with your favorite side dish or accompaniment.",
  ]

},
{
  'id': 9,
  'title': 'lemon rice',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw2yVL9fnGDxBPOzwW2n89EV8l4K8an7kMcQ&usqp=CAU',
  'time': 50,
  'isVeg': true,
  'category': 'veg',
  'rating': 3,
  'description': 'Spicy and flavorful Indian fried chicken bites, a crowd-pleaser on your Food Recipe App',
  'ingredients': ['1 cup cooked rice,', '2 tablespoons oil,', '1/2 teaspoon mustard seeds,', '1/2 teaspoon cumin seeds,', '1/4 teaspoon asafoetida,', '8-10 curry leaves,', '2-3 dry red chilies,', '1/4 cup roasted peanuts,', '1/4 cup cashew nuts,', '1/2 teaspoon turmeric powder,', '1 tablespoon lemon juice,', 'Salt to taste,', 'Chopped coriander leaves for garnishing,'],
  'procedure': [
    "Heat oil in a pan or wok over medium heat.",
    "Add mustard seeds and let them splutter.",
    "Add cumin seeds, asafoetida, curry leaves, and dry red chilies. Sauté for a minute.",
    "Add roasted peanuts and cashew nuts. Sauté until they are lightly browned.",
    "Add turmeric powder and mix well.",
    "Add the cooked rice and mix gently to coat the rice with the spices.",
    "Add lemon juice and salt. Mix well and cook for a few minutes.",
    "Remove from heat and let the lemon rice cool down slightly.",
    "Garnish with chopped coriander leaves.",
    "Serve the tangy and flavorful lemon rice as a delicious side dish or main course."
  ]

},
{
  'id': 10,
  'title': 'cocunut rice',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSffkNYPdRB5PSzWB5UHXIKvc5cIQCjc53uDg&usqp=CAU',
  'time': 60,
  'isVeg': true,
  'category': 'veg',
  'rating': 2,
  'description': 'Aromatic South Indian dish with fluffy rice and coconut, a tropical delight on Food Recipe App!',
  'ingredients': ['1 cup cooked rice,', '1 tablespoon oil,', '1/2 teaspoon mustard seeds,', '1/2 teaspoon urad dal,', '1/2 teaspoon chana dal,', '8-10 curry leaves,', '2-3 dry red chilies,', '1/4 cup grated coconut,', '2 tablespoons roasted peanuts,', '1 tablespoon cashew nuts,', '1/2 teaspoon turmeric powder,', 'Salt to taste,', 'Chopped coriander leaves for garnishing,'],
  'procedure': [
    "Heat oil in a pan or wok over medium heat.",
    "Add mustard seeds and let them splutter.",
    "Add urad dal and chana dal. Sauté until they turn golden brown.",
    "Add curry leaves and dry red chilies. Sauté for a minute.",
    "Add roasted peanuts and cashew nuts. Sauté until they are lightly browned.",
    "Add turmeric powder and mix well.",
    "Add the cooked rice and grated coconut. Mix gently to combine everything.",
    "Add salt and mix well. Cook for a few minutes.",
    "Remove from heat and let the coconut rice cool down slightly.",
    "Garnish with chopped coriander leaves.",
    "Serve the fragrant and flavorful coconut rice as a delightful side dish or main course."
  ]

},
{
  'id': 11,
  'title': 'chicken Curry',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfxlT4bD95kM6ClFBDwjVbWTSX7-LIWN6_1A&usqp=CAU',
  'time': 90,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 4,
  'description': 'Rich and tangy South Indian chicken curry, ',
  'ingredients': ['500g chicken pieces,', '2 tablespoons oil,', '1 large onion finely chopped,', '1 teaspoon ginger paste,', '1 teaspoon garlic paste,', '2 tomatoes -pureed,', '1 teaspoon turmeric powder,', '1 teaspoon red chili powder,', '1 teaspoon coriander powder,', '1/2 teaspoon cumin powder,', '1/2 teaspoon garam masala,', 'Salt to taste,', 'Fresh coriander leaves for garnishing,'],
  'procedure': [
    "Heat oil in a pan over medium heat.",
    "Add chopped onions and sauté until they turn translucent.",
    "Add ginger paste and garlic paste. Sauté for a minute until fragrant.",
    "Add the chicken pieces and cook until they are no longer pink on the outside.",
    "Add turmeric powder, red chili powder, coriander powder, cumin powder, and salt. Mix well.",
    "Add tomato puree and cook until the oil starts to separate from the masala.",
    "Add water as needed and bring the curry to a simmer. Cover and cook until the chicken is tender.",
    "Add garam masala and mix well.",
    "Garnish with chopped fresh coriander leaves.",
    "Serve the flavorful chicken curry with rice, roti, or naan for a satisfying meal."
  ]

},
{
  'id': 12,
  'title': 'Mutton Briyani',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlcvpjlHOGf3mYjpM-LsOIRK5zTvxcOnS8Cw&usqp=CAU',
  'time': 120,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 4,
  'description': 'Exquisite blend of fragrant rice and tender mutton, a royal indulgence on Food Recipe App!',
  'ingredients': ['500g mutton pieces,', '2 cups basmati rice,', '3 tablespoons ghee,', '2 tablespoons oil,', '2 large onions (sliced),', '1 teaspoon ginger paste,', '1 teaspoon garlic paste,', '2 tomatoes (chopped),', '1/2 cup yogurt,', '1 teaspoon red chili powder,', '1/2 teaspoon turmeric powder,', '1 teaspoon biryani masala,', '1/2 teaspoon garam masala,', '1/2 teaspoon cumin powder,', '1/2 teaspoon coriander powder,', '4-6 green chilies (slit),', 'A few saffron strands soaked in warm milk,', 'Fresh coriander leaves for garnishing,', 'Fried onions for garnishing,', 'Salt to taste,', 'Water for cooking rice,'],
  'procedure': [
    "Wash the basmati rice and soak it in water for about 30 minutes. Drain and set aside.",
    "Heat ghee and oil in a large heavy-bottomed pot over medium heat.",
    "Add sliced onions and sauté until they turn golden brown. Remove half of the fried onions and set aside for garnishing.",
    "Add ginger paste and garlic paste to the remaining onions. Sauté until fragrant.",
    "Add mutton pieces and brown them on all sides.",
    "Add chopped tomatoes and cook until they soften.",
    "Add red chili powder, turmeric powder, cumin powder, coriander powder, biryani masala, and salt. Mix well.",
    "Add yogurt and mix again. Cook until the oil starts to separate from the masala.",
    "Add water and bring the mixture to a boil. Cover and simmer until the mutton is tender and cooked through.",
    "In a separate pot, boil water and cook the soaked rice until it is 70-80% cooked. Drain and set aside.",
    "Layer the cooked mutton masala and rice in the same pot in alternate layers.",
    "Sprinkle garam masala, saffron milk, fried onions, and chopped fresh coriander leaves on top.",
    "Cover the pot with a tight-fitting lid and cook on low heat for about 20-25 minutes, allowing the flavors to meld.",
    "Turn off the heat and let the biryani rest for 10-15 minutes before serving.",
    "Gently fluff the rice with a fork before serving. Serve the aromatic mutton biryani with raita and salad for a delicious meal."
  ]

},
{
  'id': 13,
  'title': 'Fish Curry',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwDm--mFZ00dwhD1YwQMTNsQXS9gfSQnm-CQ&usqp=CAU',
  'time': 80,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 5,
  'description': 'Delectable fish immersed in aromatic curry, a savory delight on Food Recipe App!',
  'ingredients': ['500g fish fillets,', '2 onions (sliced),', '2 tomatoes (chopped),', '1 teaspoon ginger paste,', '1 teaspoon garlic paste,', '2 green chilies (slit),', '1/2 teaspoon turmeric powder,', '1 teaspoon red chili powder,', '1 teaspoon coriander powder,', '1/2 teaspoon cumin powder,', '1/2 teaspoon mustard seeds,', '1/2 teaspoon fenugreek seeds,', '1/2 teaspoon fennel seeds,', 'A few curry leaves,', 'Tamarind pulp (from a small lemon-sized tamarind ball),', '1 cup coconut milk,', '2 tablespoons oil,', 'Salt to taste,', 'Fresh coriander leaves for garnishing,'],
  'procedure': [
    "Clean and wash the fish fillets. Marinate them with turmeric powder and a pinch of salt. Set aside for about 15-20 minutes.",
    "Heat oil in a pan and shallow fry the marinated fish fillets until they turn golden brown. Remove and set aside.",
    "In the same pan, add mustard seeds, fenugreek seeds, and fennel seeds. Let them splutter.",
    "Add sliced onions and sauté until they become translucent.",
    "Add ginger paste and garlic paste. Sauté until the raw smell disappears.",
    "Add chopped tomatoes and cook until they soften and the oil starts to separate from the masala.",
    "Add red chili powder, coriander powder, cumin powder, and turmeric powder. Mix well.",
    "Add tamarind pulp, slit green chilies, and curry leaves. Cook for a couple of minutes.",
    "Add coconut milk and salt. Mix and bring the curry to a gentle simmer.",
    "Add the fried fish fillets into the curry. Cover and let the fish cook in the curry for about 5-7 minutes.",
    "Once the fish is cooked through, turn off the heat.",
    "Garnish with freshly chopped coriander leaves.",
    "Serve the delicious fish curry with steamed rice, roti, or bread for a flavorful meal."
  ]

},
{
  'id': 14,
  'title': 'haleem',
  'imageuri': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShP-XJN_p8R7NC9-skSRpcZdWv4oz2JciRTg&usqp=CAU',
  'time': 130,
  'isVeg': false,
  'category': 'non-veg',
  'rating': 4,
  'description': 'Hearty and wholesome stew of meat, wheat, and lentils, a Ramadan favorite on Food Recipe App',
  'ingredients': ['1 cup mixed lentils (chana dal, moong dal, masoor dal),', '1/2 cup broken wheat (daliya),', '250g boneless chicken or mutton pieces,', '2 onions (sliced),', '2 tomatoes (chopped),', '1 teaspoon ginger paste,', '1 teaspoon garlic paste,', '1/2 teaspoon turmeric powder,', '1 teaspoon red chili powder,', '1 teaspoon garam masala,', '1 teaspoon cumin powder,', '1/2 teaspoon coriander powder,', '1/2 teaspoon black pepper powder,', '1/4 teaspoon cinnamon powder,', '1/4 teaspoon nutmeg powder,', 'A pinch of saffron strands,', '2 tablespoons ghee,', '2 tablespoons cooking oil,', '1/4 cup yogurt,', 'Fresh coriander leaves for garnishing,', 'Fried onions for garnishing,', 'Lemon wedges for serving,', 'Salt to taste,'],
  'procedure': [
    "Wash the mixed lentils and broken wheat thoroughly. Soak them in water for about 2 hours.",
    "In a large pot, add the soaked lentils and broken wheat along with enough water. Cook until they become soft and mushy. You can use a pressure cooker for faster cooking.",
    "In a separate pot, heat oil and ghee. Add sliced onions and sauté until golden brown. Remove half of the fried onions for garnishing.",
    "Add ginger paste and garlic paste to the pot. Sauté until the raw smell disappears.",
    "Add chicken or mutton pieces and sauté until they turn white and are lightly browned.",
    "Add chopped tomatoes and cook until they become soft and oil starts to separate.",
    "Add all the spice powders - turmeric, red chili, garam masala, cumin, coriander, black pepper, cinnamon, nutmeg, and saffron strands. Mix well.",
    "Add yogurt and salt. Cook until the meat is tender and well-cooked.",
    "Once the lentils and broken wheat are cooked, use a hand blender to blend them into a smooth paste. Alternatively, you can use a masher to achieve the desired consistency.",
    "Add the cooked meat and its gravy to the lentil mixture. Mix well.",
    "Simmer the haleem on low heat for about 20-30 minutes, stirring occasionally to prevent sticking.",
    "Adjust the consistency by adding more water if needed. The haleem should be thick and porridge-like.",
    "Garnish with fried onions and chopped fresh coriander leaves.",
    "Serve the delicious haleem hot with lemon wedges, naan, or roti for a hearty and comforting meal."
  ]
},
{
  "id": 15,
  "title": "Paneer Tikka",
  "imageuri": "https://www.indianveggiedelight.com/wp-content/uploads/2021/08/air-fryer-paneer-tikka-featured.jpg",
  "time": 45,
  "isVeg": true,
  "category": "veg",
  "rating": 4,
  "description": "Tasty marinated paneer pieces grilled to perfection",
  "ingredients": [
    "200g paneer cubes",
    "1/2 cup yogurt",
    "1 tablespoon ginger-garlic paste",
    "1 teaspoon red chili powder",
    "1 teaspoon turmeric powder",
    "1 teaspoon garam masala",
    "1 tablespoon lemon juice",
    "Salt to taste",
    "1 tablespoon oil",
    "Bell peppers and onions for skewering"
  ],
  "procedure": [
    "In a bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, lemon juice, salt, and oil to make the marinade.",
    "Add paneer cubes and let them marinate for about 30 minutes.",
    "Thread the marinated paneer cubes, bell peppers, and onions onto skewers.",
    "Preheat a grill or grill pan over medium-high heat.",
    "Grill the skewers, turning occasionally, until the paneer and veggies are charred and cooked.",
    "Serve the flavorful paneer tikka with mint chutney or sauce."
  ]
},
{
  "id": 16,
  "title": "Mushroom Risotto",
  "imageuri": "https://www.afamilyfeast.com/wp-content/uploads/2012/11/Mushroom-Risotto-3.jpg",
  "time": 40,
  "isVeg": true,
  "category": "veg",
  "rating": 4,
  "description": "Creamy Italian rice dish cooked with mushrooms and parmesan",
  "ingredients": [
    "1 cup Arborio rice",
    "200g mushrooms, sliced",
    "1/2 cup white wine",
    "4 cups vegetable broth",
    "1 small onion, finely chopped",
    "2 cloves garlic, minced",
    "2 tablespoons butter",
    "1/2 cup grated parmesan cheese",
    "Salt and black pepper to taste",
    "Fresh parsley for garnishing"
  ],
  "procedure": [
    "In a saucepan, heat vegetable broth and keep it warm.",
    "In a large skillet, melt butter and sauté onions and garlic until translucent.",
    "Add Arborio rice and cook for a few minutes until the rice is lightly toasted.",
    "Pour in the white wine and cook until it's mostly absorbed.",
    "Gradually add warm vegetable broth, one ladleful at a time, stirring frequently and allowing the liquid to be absorbed before adding more.",
    "Stir in sliced mushrooms and continue adding broth until the rice is creamy and cooked.",
    "Stir in grated parmesan cheese and season with salt and black pepper.",
    "Garnish with fresh parsley and serve the creamy mushroom risotto."
  ]
},
{
  "id": 17,
  "title": "Chole Bhature",
  "imageuri": "https://www.spiceupthecurry.com/wp-content/uploads/2015/03/Chole-bhature-1.jpg",
  "time": 90,
  "isVeg": true,
  "category": "veg",
  "rating": 4.2,
  "description": "Spiced chickpea curry served with deep-fried bread called bhature",
  "ingredients": [
    "1 cup chickpeas (chole), soaked overnight",
    "2 onions, finely chopped",
    "2 tomatoes, pureed",
    "1 tablespoon ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon turmeric powder",
    "1 teaspoon red chili powder",
    "1 teaspoon garam masala",
    "1 teaspoon cumin powder",
    "1 teaspoon coriander powder",
    "1/2 teaspoon amchur (dry mango) powder",
    "1/2 teaspoon baking soda",
    "Fresh coriander leaves for garnishing",
    "Oil for frying",
    "Salt to taste"
  ],
  "procedure": [
    "Boil soaked chickpeas with baking soda until they are soft and cooked.",
    "Heat oil in a pan. Add cumin seeds and let them splutter.",
    "Add chopped onions and sauté until golden brown.",
    "Stir in ginger-garlic paste and sauté until aromatic.",
    "Add tomato puree and cook until the oil separates from the mixture.",
    "Add turmeric powder, red chili powder, coriander powder, cumin powder, amchur powder, and salt. Cook the spices.",
    "Add cooked chickpeas and garam masala. Mix well and simmer for a few minutes.",
    "For bhature, knead dough with flour, yogurt, and baking soda. Let it rest.",
    "Roll out small rounds of dough and deep-fry until puffed and golden.",
    "Serve hot chole with bhature and garnish with fresh coriander leaves."
  ]
},
{
  "id": 18,
  "title": "Sambar",
  "imageuri": "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/05/sambar.jpg",
  "time": 40,
  "isVeg": true,
  "category": "veg",
  "rating": 4.6,
  "description": "Spicy lentil and vegetable stew, served with rice or idli/dosa",
  "ingredients": [
    "1/2 cup toor dal (pigeon pea lentils)",
    "1 cup mixed vegetables (carrots, beans, eggplant, etc.)",
    "1 onion, chopped",
    "2 tomatoes, chopped",
    "1/4 cup tamarind pulp",
    "1 tablespoon sambar powder",
    "1/2 teaspoon turmeric powder",
    "1/2 teaspoon mustard seeds",
    "A pinch of asafoetida (hing)",
    "A few curry leaves",
    "2 tablespoons oil",
    "Salt to taste"
  ],
  "procedure": [
    "Pressure-cook toor dal until soft. Mash and set aside.",
    "Cook mixed vegetables until tender. Set aside.",
    "In a pot, heat oil and add mustard seeds. Let them splutter.",
    "Add chopped onions and sauté until golden.",
    "Add tomatoes, sambar powder, turmeric powder, and salt. Cook until tomatoes are soft.",
    "Add tamarind pulp and cooked vegetables. Mix well.",
    "Add mashed toor dal and enough water to achieve the desired consistency.",
    "Bring the sambar to a boil and let it simmer for a few minutes.",
    "In a separate pan, heat some oil and add mustard seeds, curry leaves, and asafoetida. Add this tempering to the sambar.",
    "Serve sambar with rice, idli, or dosa."
  ]
},
{
  "id": 19,
  "title": "Prawn Fry",
  "imageuri": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3BvWTlmEbvahIgO_Ubp1Vj8l3XorWGsQ-dg&usqp=CAU",
  "time": 25,
  "isVeg": false,
  "category": "non-veg",
  "rating": 4.8,
  "description": "Spicy and flavorful fried prawns, perfect as an appetizer or side dish.",
  "ingredients": [
    "250 grams prawns, cleaned and deveined",
    "2 tablespoons oil",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon red chili powder",
    "1/2 teaspoon turmeric powder",
    "1 teaspoon cumin powder",
    "1 teaspoon coriander powder",
    "1/2 teaspoon black pepper powder",
    "Salt to taste",
    "Fresh coriander leaves, chopped (for garnish)"
  ],
  "procedure": [
    "Marinate the cleaned prawns with ginger-garlic paste, red chili powder, turmeric powder, cumin powder, coriander powder, black pepper powder, and salt. Let it sit for 15-20 minutes.",
    "Heat oil in a pan over medium heat.",
    "Add the marinated prawns to the pan and spread them out in a single layer.",
    "Cook the prawns for about 2-3 minutes on each side until they turn pink and opaque.",
    "Remove the prawns from the pan and drain excess oil on a paper towel.",
    "Garnish with chopped fresh coriander leaves.",
    "Serve the prawn fry hot as an appetizer or side dish."
  ]
},
{
  "id": 20,
  "title": "Crab Curry",
  "imageuri": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQq3UkqYd4qDc6qft_Tn0XG3cHumyLu1AwAww&usqp=CAU",
  "time": 40,
  "isVeg": false,
  "category": "main course",
  "rating": 4.7,
  "description": "A rich and flavorful curry made with crab, perfect to be enjoyed with rice or bread.",
  "ingredients": [
    "500 grams crabs, cleaned and washed",
    "1 large onion, finely chopped",
    "2 tomatoes, chopped",
    "2 tablespoons oil",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon cumin seeds",
    "1 teaspoon fennel seeds",
    "1/2 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 teaspoon coriander powder",
    "1/2 teaspoon black pepper powder",
    "1/2 teaspoon garam masala",
    "A pinch of asafoetida (hing)",
    "Few curry leaves",
    "Fresh coriander leaves, chopped (for garnish)",
    "Salt to taste"
  ],
  "procedure": [
    "Heat oil in a pan or pot. Add cumin seeds and fennel seeds. Let them splutter.",
    "Add chopped onions and sauté until they turn golden brown.",
    "Add ginger-garlic paste and sauté until the raw smell dissipates.",
    "Add the chopped tomatoes and cook until they turn soft.",
    "Add turmeric powder, red chili powder, coriander powder, black pepper powder, garam masala, and asafoetida. Mix well and cook for a few minutes.",
    "Add the cleaned crabs to the masala and mix thoroughly so that the masala coats the crabs well.",
    "Add curry leaves and salt. Mix again.",
    "Cover the pan or pot and let the crabs cook in their own juices for about 15-20 minutes, stirring occasionally. You can also add a little water if needed.",
    "Once the crabs are cooked and the gravy has thickened, remove from heat.",
    "Garnish with chopped fresh coriander leaves.",
    "Serve the crab curry hot with steamed rice or bread of your choice."
  ]
},
{
  "id": 21,
  "title": "Squid Curry",
  "imageuri": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJcrZiajHHlQ2bhEcTfa8LTdWd-mxn1g939w&usqp=CAU",
  "time": 35,
  "isVeg": false,
  "category": "non-veg",
  "rating": 4.6,
  "description": "A flavorful and aromatic squid curry cooked in a traditional South Indian style.",
  "ingredients": [
    "500 grams squid, cleaned and cut into rings",
    "1 large onion, finely chopped",
    "2 tomatoes, chopped",
    "2 tablespoons oil",
    "1 teaspoon mustard seeds",
    "1 teaspoon cumin seeds",
    "10-12 curry leaves",
    "1 teaspoon ginger-garlic paste",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "1 tablespoon coriander powder",
    "1/2 teaspoon fennel seeds",
    "1/2 teaspoon fenugreek seeds",
    "1/2 teaspoon cumin powder",
    "1/2 teaspoon black pepper powder",
    "1/2 teaspoon garam masala",
    "2 tablespoons coconut milk",
    "Tamarind pulp (extracted from a small piece of tamarind soaked in water)",
    "Salt to taste",
    "Fresh coriander leaves, chopped (for garnish)"
  ],
  "procedure": [
    "Heat oil in a pan. Add mustard seeds and let them splutter.",
    "Add cumin seeds, fennel seeds, and fenugreek seeds. Sauté for a minute until aromatic.",
    "Add chopped onions and sauté until they turn golden brown.",
    "Add curry leaves and ginger-garlic paste. Sauté for a minute until the raw smell disappears.",
    "Add chopped tomatoes and cook until they become soft and pulpy.",
    "Add turmeric powder, red chili powder, coriander powder, cumin powder, black pepper powder, and garam masala. Mix well and cook for a couple of minutes.",
    "Add the cleaned squid rings and mix with the masala. Cook for 3-4 minutes on medium heat.",
    "Add tamarind pulp, coconut milk, and salt. Mix well and bring the curry to a gentle simmer.",
    "Cover the pan and let the squid cook in the curry for about 15-20 minutes, stirring occasionally. Add water if needed to adjust the consistency.",
    "Once the squid is tender and the flavors are well blended, remove from heat.",
    "Garnish with chopped fresh coriander leaves.",
    "Serve the squid curry hot with steamed rice or bread."
  ]
},
{
  "id": 22,
  "title": "Mutton Curry",
  "imageuri": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLOSStqWuRiJgXXO6txChRtaip17tr0CK6WQ&usqp=CAU",
  "time": 60,
  "isVeg": false,
  "category": "non-veg",
  "rating": 4.8,
  "description": "A rich and flavorful mutton curry made with tender pieces of mutton cooked in aromatic spices.",
  "ingredients": [
    "750 grams mutton, cut into pieces",
    "2 large onions, finely sliced",
    "2 tomatoes, chopped",
    "2 tablespoons oil",
    "1 teaspoon cumin seeds",
    "4-5 cloves",
    "4-5 green cardamom pods",
    "1 cinnamon stick",
    "1 bay leaf",
    "1 teaspoon ginger paste",
    "1 teaspoon garlic paste",
    "1 teaspoon turmeric powder",
    "2 teaspoons red chili powder",
    "2 teaspoons coriander powder",
    "1/2 teaspoon cumin powder",
    "1/2 teaspoon garam masala",
    "Salt to taste",
    "Fresh coriander leaves, chopped (for garnish)"
  ],
  "procedure": [
    "Heat oil in a large pot. Add cumin seeds, cloves, cardamom pods, cinnamon stick, and bay leaf. Sauté for a minute until aromatic.",
    "Add sliced onions and sauté until they turn golden brown.",
    "Add ginger paste and garlic paste. Sauté for a minute until the raw smell disappears.",
    "Add chopped tomatoes and cook until they become soft and pulpy.",
    "Add turmeric powder, red chili powder, coriander powder, cumin powder, and garam masala. Mix well and cook for a couple of minutes.",
    "Add the mutton pieces and salt. Mix with the masala and cook for 5-7 minutes until the mutton starts to brown.",
    "Add enough water to cover the mutton and bring to a boil. Reduce the heat to low, cover the pot, and let it simmer for about 45-50 minutes or until the mutton is tender and cooked through.",
    "Once the mutton is cooked and the gravy has thickened, remove from heat.",
    "Garnish with chopped fresh coriander leaves.",
    "Serve the mutton curry hot with rice, naan, or roti."
  ]
},
]
